version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_management_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5431"
    command: -p 5431
    networks:
      - library-prod-network

  backend:
    build:
      context: ./library-management-backend
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5431/library_management_prod
      - NODE_ENV=production
      - PORT=8001
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    networks:
      - library-prod-network

  frontend:
    build:
      context: ./library-management-frontend
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - library-prod-network

volumes:
  postgres_data:

networks:
  library-prod-network:
    driver: bridge
