version: "3.8"
services:
  db:
    image: postgres:15-alpine
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  api:
    container_name: library-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/library_management
      - PORT=8000
    #command: ["sh", "/app/scripts/startDev.sh"]
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - library-network

volumes:
  postgres-data:

networks:
  library-network:
    driver: bridge
