FROM node:18-alpine

WORKDIR /app

COPY package.json ./
RUN apk add --no-cache openssl

RUN apk add --no-cache --virtual builds-deps build-base python3

RUN yarn install

COPY prisma ./prisma/
COPY tsconfig.json ./
COPY src ./src/

ENV PRISMA_BINARY_PLATFORM=linux-musl
RUN yarn prisma generate

RUN yarn build

EXPOSE 8001

CMD ["yarn", "start"]
