# Stage 1
FROM node:20-alpine as builder
RUN apk update && apk add git
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./

RUN yarn
COPY . ./

ENV APP_ENV=prod
ENV API_URL=http://localhost:8001

RUN yarn build

# Stage 2
FROM nginx:stable-alpine
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 4000
ENTRYPOINT ["nginx", "-g", "daemon off;"]
